spring:
  application:
    name: washify-api
  profiles:
    [cite_start]active: dev # Setăm 'dev' ca profil implicit pentru dezvoltarea locală
  jackson:
    serialization:
      write-dates-as-timestamps: false # Bună practică pentru formate ISO-8601